///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace sample_1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
	/// <summary>
	/// The class representing the sample_1Repository element repository.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
	[RepositoryFolder("c6f2f9b9-9017-475b-bb67-96a89cccf04e")]
	public partial class sample_1Repository : RepoGenBaseFolder
	{
		static sample_1Repository instance = new sample_1Repository();
		sample_1RepositoryFolders.RxMainFrameAppFolder _rxmainframe;
		sample_1RepositoryFolders.List1000AppFolder _list1000;
		sample_1RepositoryFolders.WindowsApp電卓AppFolder _windowsapp電卓;

		/// <summary>
		/// Gets the singleton class instance representing the sample_1Repository element repository.
		/// </summary>
		[RepositoryFolder("c6f2f9b9-9017-475b-bb67-96a89cccf04e")]
		public static sample_1Repository Instance
		{
			get { return instance; }
		}

		/// <summary>
		/// Repository class constructor.
		/// </summary>
		public sample_1Repository() 
			: base("sample_1Repository", "/", null, 0, false, "c6f2f9b9-9017-475b-bb67-96a89cccf04e", ".\\RepositoryImages\\sample_1Repositoryc6f2f9b9.rximgres")
		{
			_rxmainframe = new sample_1RepositoryFolders.RxMainFrameAppFolder(this);
			_list1000 = new sample_1RepositoryFolders.List1000AppFolder(this);
			_windowsapp電卓 = new sample_1RepositoryFolders.WindowsApp電卓AppFolder(this);
		}

#region Variables

#endregion

		/// <summary>
		/// The Self item info.
		/// </summary>
		[RepositoryItemInfo("c6f2f9b9-9017-475b-bb67-96a89cccf04e")]
		public virtual RepoItemInfo SelfInfo
		{
			get
			{
				return _selfInfo;
			}
		}

		/// <summary>
		/// The RxMainFrame folder.
		/// </summary>
		[RepositoryFolder("5ffe4bba-5a3a-4b04-940a-ed9df8392305")]
		public virtual sample_1RepositoryFolders.RxMainFrameAppFolder RxMainFrame
		{
			get { return _rxmainframe; }
		}

		/// <summary>
		/// The List1000 folder.
		/// </summary>
		[RepositoryFolder("b3e9e1db-2ce3-4c39-9f2c-d1754c088064")]
		public virtual sample_1RepositoryFolders.List1000AppFolder List1000
		{
			get { return _list1000; }
		}

		/// <summary>
		/// The WindowsApp電卓 folder.
		/// </summary>
		[RepositoryFolder("0da3aa8b-f7df-4a72-b48c-006148b8f305")]
		public virtual sample_1RepositoryFolders.WindowsApp電卓AppFolder WindowsApp電卓
		{
			get { return _windowsapp電卓; }
		}
	}

	/// <summary>
	/// Inner folder classes.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
	public partial class sample_1RepositoryFolders
	{
		/// <summary>
		/// The RxMainFrameAppFolder folder.
		/// </summary>
		[RepositoryFolder("5ffe4bba-5a3a-4b04-940a-ed9df8392305")]
		public partial class RxMainFrameAppFolder : RepoGenBaseFolder
		{
			sample_1RepositoryFolders.RxTabStandardFolder _rxtabstandard;
			sample_1RepositoryFolders.RxTabUIElementsFolder _rxtabuielements;
			RepoItemInfo _enteryournameInfo;
			RepoItemInfo _btnsubmitusernameInfo;
			RepoItemInfo _rxbuttonexitInfo;
			RepoItemInfo _testdatabaseInfo;
			RepoItemInfo _uielementtestareaInfo;
			RepoItemInfo _uploadtestingInfo;
			RepoItemInfo _rbslowInfo;
			RepoItemInfo _resetuploadInfo;
			RepoItemInfo _imagebasedautomationInfo;

			/// <summary>
			/// Creates a new RxMainFrame  folder.
			/// </summary>
			public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
					base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "5ffe4bba-5a3a-4b04-940a-ed9df8392305", "")
			{
				_rxtabstandard = new sample_1RepositoryFolders.RxTabStandardFolder(this);
				_rxtabuielements = new sample_1RepositoryFolders.RxTabUIElementsFolder(this);
				_enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/tabpage[@controlname='RxTabIntroduction']/?/?/text[@accessiblename='Enter your name']", 30000, null, "10a6ab0c-98cc-49bd-aaa4-9d553ba73266");
				_btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "?/?/tabpage[@controlname='RxTabIntroduction']/button[@controlname='btnSubmitUserName']", 30000, null, "7bed0da2-f91d-4a7f-b32a-010a64e4c761");
				_rxbuttonexitInfo = new RepoItemInfo(this, "RxButtonExit", "button[@controlname='RxButtonExit']", 30000, null, "a023ef5c-9f81-4a22-ad2b-3ae166b4a780");
				_testdatabaseInfo = new RepoItemInfo(this, "TestDatabase", "?/?/tabpage[@accessiblename='Test database']", 30000, null, "8176269e-df18-4699-be28-361ce42dd46c");
				_uielementtestareaInfo = new RepoItemInfo(this, "UIElementTestArea", "?/?/tabpage[@accessiblename='UI-element test area']", 30000, null, "b49fdc9d-63b5-4c52-bf81-9ac6057dc250");
				_uploadtestingInfo = new RepoItemInfo(this, "UploadTesting", "?/?/tabpage[@accessiblename='Upload testing']", 30000, null, "fa270ec3-c804-48e0-882a-c5d5a8a844ea");
				_rbslowInfo = new RepoItemInfo(this, "RBSlow", "?/?/tabpage[@controlname='RxTabUpload']/?/?/radiobutton[@controlname='rBSlow']", 30000, null, "4e1ea780-6a69-41f5-8bdd-a763242c87c9");
				_resetuploadInfo = new RepoItemInfo(this, "ResetUpload", "?/?/tabpage[@controlname='RxTabUpload']/?/?/element[@accessiblename='Reset upload']", 30000, null, "f0637e0e-2951-4058-a29b-4956bd8a630a");
				_imagebasedautomationInfo = new RepoItemInfo(this, "ImageBasedAutomation", "?/?/tabpage[@accessiblename='Image-based automation']", 30000, null, "d7688285-9bba-44a7-a8a1-218d389c4bbb");
			}

			/// <summary>
			/// The Self item.
			/// </summary>
			[RepositoryItem("5ffe4bba-5a3a-4b04-940a-ed9df8392305")]
			public virtual Ranorex.Form Self
			{
				get
				{
					return _selfInfo.CreateAdapter<Ranorex.Form>(true);
				}
			}

			/// <summary>
			/// The Self item info.
			/// </summary>
			[RepositoryItemInfo("5ffe4bba-5a3a-4b04-940a-ed9df8392305")]
			public virtual RepoItemInfo SelfInfo
			{
				get
				{
					return _selfInfo;
				}
			}

			/// <summary>
			/// The EnterYourName item.
			/// </summary>
			[RepositoryItem("10a6ab0c-98cc-49bd-aaa4-9d553ba73266")]
			public virtual Ranorex.Text EnterYourName
			{
				get
				{
					return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
				}
			}

			/// <summary>
			/// The EnterYourName item info.
			/// </summary>
			[RepositoryItemInfo("10a6ab0c-98cc-49bd-aaa4-9d553ba73266")]
			public virtual RepoItemInfo EnterYourNameInfo
			{
				get
				{
					return _enteryournameInfo;
				}
			}

			/// <summary>
			/// The BtnSubmitUserName item.
			/// </summary>
			[RepositoryItem("7bed0da2-f91d-4a7f-b32a-010a64e4c761")]
			public virtual Ranorex.Button BtnSubmitUserName
			{
				get
				{
					return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The BtnSubmitUserName item info.
			/// </summary>
			[RepositoryItemInfo("7bed0da2-f91d-4a7f-b32a-010a64e4c761")]
			public virtual RepoItemInfo BtnSubmitUserNameInfo
			{
				get
				{
					return _btnsubmitusernameInfo;
				}
			}

			/// <summary>
			/// The RxButtonExit item.
			/// </summary>
			[RepositoryItem("a023ef5c-9f81-4a22-ad2b-3ae166b4a780")]
			public virtual Ranorex.Button RxButtonExit
			{
				get
				{
					return _rxbuttonexitInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The RxButtonExit item info.
			/// </summary>
			[RepositoryItemInfo("a023ef5c-9f81-4a22-ad2b-3ae166b4a780")]
			public virtual RepoItemInfo RxButtonExitInfo
			{
				get
				{
					return _rxbuttonexitInfo;
				}
			}

			/// <summary>
			/// The TestDatabase item.
			/// </summary>
			[RepositoryItem("8176269e-df18-4699-be28-361ce42dd46c")]
			public virtual Ranorex.TabPage TestDatabase
			{
				get
				{
					return _testdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
				}
			}

			/// <summary>
			/// The TestDatabase item info.
			/// </summary>
			[RepositoryItemInfo("8176269e-df18-4699-be28-361ce42dd46c")]
			public virtual RepoItemInfo TestDatabaseInfo
			{
				get
				{
					return _testdatabaseInfo;
				}
			}

			/// <summary>
			/// The UIElementTestArea item.
			/// </summary>
			[RepositoryItem("b49fdc9d-63b5-4c52-bf81-9ac6057dc250")]
			public virtual Ranorex.TabPage UIElementTestArea
			{
				get
				{
					return _uielementtestareaInfo.CreateAdapter<Ranorex.TabPage>(true);
				}
			}

			/// <summary>
			/// The UIElementTestArea item info.
			/// </summary>
			[RepositoryItemInfo("b49fdc9d-63b5-4c52-bf81-9ac6057dc250")]
			public virtual RepoItemInfo UIElementTestAreaInfo
			{
				get
				{
					return _uielementtestareaInfo;
				}
			}

			/// <summary>
			/// The UploadTesting item.
			/// </summary>
			[RepositoryItem("fa270ec3-c804-48e0-882a-c5d5a8a844ea")]
			public virtual Ranorex.TabPage UploadTesting
			{
				get
				{
					return _uploadtestingInfo.CreateAdapter<Ranorex.TabPage>(true);
				}
			}

			/// <summary>
			/// The UploadTesting item info.
			/// </summary>
			[RepositoryItemInfo("fa270ec3-c804-48e0-882a-c5d5a8a844ea")]
			public virtual RepoItemInfo UploadTestingInfo
			{
				get
				{
					return _uploadtestingInfo;
				}
			}

			/// <summary>
			/// The RBSlow item.
			/// </summary>
			[RepositoryItem("4e1ea780-6a69-41f5-8bdd-a763242c87c9")]
			public virtual Ranorex.RadioButton RBSlow
			{
				get
				{
					return _rbslowInfo.CreateAdapter<Ranorex.RadioButton>(true);
				}
			}

			/// <summary>
			/// The RBSlow item info.
			/// </summary>
			[RepositoryItemInfo("4e1ea780-6a69-41f5-8bdd-a763242c87c9")]
			public virtual RepoItemInfo RBSlowInfo
			{
				get
				{
					return _rbslowInfo;
				}
			}

			/// <summary>
			/// The ResetUpload item.
			/// </summary>
			[RepositoryItem("f0637e0e-2951-4058-a29b-4956bd8a630a")]
			public virtual Ranorex.Unknown ResetUpload
			{
				get
				{
					return _resetuploadInfo.CreateAdapter<Ranorex.Unknown>(true);
				}
			}

			/// <summary>
			/// The ResetUpload item info.
			/// </summary>
			[RepositoryItemInfo("f0637e0e-2951-4058-a29b-4956bd8a630a")]
			public virtual RepoItemInfo ResetUploadInfo
			{
				get
				{
					return _resetuploadInfo;
				}
			}

			/// <summary>
			/// The ImageBasedAutomation item.
			/// </summary>
			[RepositoryItem("d7688285-9bba-44a7-a8a1-218d389c4bbb")]
			public virtual Ranorex.TabPage ImageBasedAutomation
			{
				get
				{
					return _imagebasedautomationInfo.CreateAdapter<Ranorex.TabPage>(true);
				}
			}

			/// <summary>
			/// The ImageBasedAutomation item info.
			/// </summary>
			[RepositoryItemInfo("d7688285-9bba-44a7-a8a1-218d389c4bbb")]
			public virtual RepoItemInfo ImageBasedAutomationInfo
			{
				get
				{
					return _imagebasedautomationInfo;
				}
			}

			/// <summary>
			/// The RxTabStandard folder.
			/// </summary>
			[RepositoryFolder("1be18d95-6059-4db8-9d69-ea57ec45bc43")]
			public virtual sample_1RepositoryFolders.RxTabStandardFolder RxTabStandard
			{
				get { return _rxtabstandard; }
			}

			/// <summary>
			/// The RxTabUIElements folder.
			/// </summary>
			[RepositoryFolder("f08654ce-2eec-4bfd-b90d-36e5d1965cc1")]
			public virtual sample_1RepositoryFolders.RxTabUIElementsFolder RxTabUIElements
			{
				get { return _rxtabuielements; }
			}
		}

		/// <summary>
		/// The RxTabStandardFolder folder.
		/// </summary>
		[RepositoryFolder("1be18d95-6059-4db8-9d69-ea57ec45bc43")]
		public partial class RxTabStandardFolder : RepoGenBaseFolder
		{
			RepoItemInfo _rdbmaleInfo;
			RepoItemInfo _firstnameInfo;
			RepoItemInfo _lastnameInfo;
			RepoItemInfo _btnaddpersonInfo;
			RepoItemInfo _btndeletepersonInfo;
			RepoItemInfo _cmbdepartmentInfo;
			RepoItemInfo _button上へInfo;
			RepoItemInfo _lstpersonlistInfo;
			RepoItemInfo _testtestmale3projectmanagementInfo;

			/// <summary>
			/// Creates a new RxTabStandard  folder.
			/// </summary>
			public RxTabStandardFolder(RepoGenBaseFolder parentFolder) :
					base("RxTabStandard", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "1be18d95-6059-4db8-9d69-ea57ec45bc43", "")
			{
				_rdbmaleInfo = new RepoItemInfo(this, "RdbMale", "?/?/radiobutton[@controlname='rdbMale']", 30000, null, "a7a43d17-9868-4c8b-adec-d9471f5a3ae7");
				_firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", 30000, null, "0fa2acf5-3247-4b34-b232-ea48067d6a1e");
				_lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", 30000, null, "3991703d-cf5d-4b24-a64d-1a00b6efac52");
				_btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", "button[@controlname='btnAddPerson']", 30000, null, "90d19ff7-6927-4a9c-a42d-25b0a9f5f792");
				_btndeletepersonInfo = new RepoItemInfo(this, "BtnDeletePerson", "button[@controlname='btnDeletePerson']", 30000, null, "da7c423d-d8f6-4bb7-92e9-2cdea40217d3");
				_cmbdepartmentInfo = new RepoItemInfo(this, "CmbDepartment", "combobox[@controlname='cmbDepartment']", 30000, null, "3bf7041e-6bc9-40a4-bb0f-8cb71c6b98e2");
				_button上へInfo = new RepoItemInfo(this, "Button上へ", "container[@controlname='txtAge']/?/?/button[@accessiblename='上へ']", 30000, null, "17401e34-178a-4dc0-975b-034e66b77d4f");
				_lstpersonlistInfo = new RepoItemInfo(this, "LstPersonList", "list[@controlname='lstPersonList']", 30000, null, "cde8989a-da12-4d86-8c8f-8ae30d689b41");
				_testtestmale3projectmanagementInfo = new RepoItemInfo(this, "TestTestMale3ProjectManagement", "list[@controlname='lstPersonList']/?/?/listitem[@accessiblename~'^test\\ test\\ \\(male,\\ 3\\)\\ Proje']", 30000, null, "a313a6f6-880b-4f31-b723-8e5920dd25bb");
			}

			/// <summary>
			/// The Self item.
			/// </summary>
			[RepositoryItem("1be18d95-6059-4db8-9d69-ea57ec45bc43")]
			public virtual Ranorex.TabPage Self
			{
				get
				{
					return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
				}
			}

			/// <summary>
			/// The Self item info.
			/// </summary>
			[RepositoryItemInfo("1be18d95-6059-4db8-9d69-ea57ec45bc43")]
			public virtual RepoItemInfo SelfInfo
			{
				get
				{
					return _selfInfo;
				}
			}

			/// <summary>
			/// The RdbMale item.
			/// </summary>
			[RepositoryItem("a7a43d17-9868-4c8b-adec-d9471f5a3ae7")]
			public virtual Ranorex.RadioButton RdbMale
			{
				get
				{
					return _rdbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
				}
			}

			/// <summary>
			/// The RdbMale item info.
			/// </summary>
			[RepositoryItemInfo("a7a43d17-9868-4c8b-adec-d9471f5a3ae7")]
			public virtual RepoItemInfo RdbMaleInfo
			{
				get
				{
					return _rdbmaleInfo;
				}
			}

			/// <summary>
			/// The FirstName item.
			/// </summary>
			[RepositoryItem("0fa2acf5-3247-4b34-b232-ea48067d6a1e")]
			public virtual Ranorex.Text FirstName
			{
				get
				{
					return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
				}
			}

			/// <summary>
			/// The FirstName item info.
			/// </summary>
			[RepositoryItemInfo("0fa2acf5-3247-4b34-b232-ea48067d6a1e")]
			public virtual RepoItemInfo FirstNameInfo
			{
				get
				{
					return _firstnameInfo;
				}
			}

			/// <summary>
			/// The LastName item.
			/// </summary>
			[RepositoryItem("3991703d-cf5d-4b24-a64d-1a00b6efac52")]
			public virtual Ranorex.Text LastName
			{
				get
				{
					return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
				}
			}

			/// <summary>
			/// The LastName item info.
			/// </summary>
			[RepositoryItemInfo("3991703d-cf5d-4b24-a64d-1a00b6efac52")]
			public virtual RepoItemInfo LastNameInfo
			{
				get
				{
					return _lastnameInfo;
				}
			}

			/// <summary>
			/// The BtnAddPerson item.
			/// </summary>
			[RepositoryItem("90d19ff7-6927-4a9c-a42d-25b0a9f5f792")]
			public virtual Ranorex.Button BtnAddPerson
			{
				get
				{
					return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The BtnAddPerson item info.
			/// </summary>
			[RepositoryItemInfo("90d19ff7-6927-4a9c-a42d-25b0a9f5f792")]
			public virtual RepoItemInfo BtnAddPersonInfo
			{
				get
				{
					return _btnaddpersonInfo;
				}
			}

			/// <summary>
			/// The BtnDeletePerson item.
			/// </summary>
			[RepositoryItem("da7c423d-d8f6-4bb7-92e9-2cdea40217d3")]
			public virtual Ranorex.Button BtnDeletePerson
			{
				get
				{
					return _btndeletepersonInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The BtnDeletePerson item info.
			/// </summary>
			[RepositoryItemInfo("da7c423d-d8f6-4bb7-92e9-2cdea40217d3")]
			public virtual RepoItemInfo BtnDeletePersonInfo
			{
				get
				{
					return _btndeletepersonInfo;
				}
			}

			/// <summary>
			/// The CmbDepartment item.
			/// </summary>
			[RepositoryItem("3bf7041e-6bc9-40a4-bb0f-8cb71c6b98e2")]
			public virtual Ranorex.ComboBox CmbDepartment
			{
				get
				{
					return _cmbdepartmentInfo.CreateAdapter<Ranorex.ComboBox>(true);
				}
			}

			/// <summary>
			/// The CmbDepartment item info.
			/// </summary>
			[RepositoryItemInfo("3bf7041e-6bc9-40a4-bb0f-8cb71c6b98e2")]
			public virtual RepoItemInfo CmbDepartmentInfo
			{
				get
				{
					return _cmbdepartmentInfo;
				}
			}

			/// <summary>
			/// The Button上へ item.
			/// </summary>
			[RepositoryItem("17401e34-178a-4dc0-975b-034e66b77d4f")]
			public virtual Ranorex.Button Button上へ
			{
				get
				{
					return _button上へInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The Button上へ item info.
			/// </summary>
			[RepositoryItemInfo("17401e34-178a-4dc0-975b-034e66b77d4f")]
			public virtual RepoItemInfo Button上へInfo
			{
				get
				{
					return _button上へInfo;
				}
			}

			/// <summary>
			/// The LstPersonList item.
			/// </summary>
			[RepositoryItem("cde8989a-da12-4d86-8c8f-8ae30d689b41")]
			public virtual Ranorex.List LstPersonList
			{
				get
				{
					return _lstpersonlistInfo.CreateAdapter<Ranorex.List>(true);
				}
			}

			/// <summary>
			/// The LstPersonList item info.
			/// </summary>
			[RepositoryItemInfo("cde8989a-da12-4d86-8c8f-8ae30d689b41")]
			public virtual RepoItemInfo LstPersonListInfo
			{
				get
				{
					return _lstpersonlistInfo;
				}
			}

			/// <summary>
			/// The TestTestMale3ProjectManagement item.
			/// </summary>
			[RepositoryItem("a313a6f6-880b-4f31-b723-8e5920dd25bb")]
			public virtual Ranorex.ListItem TestTestMale3ProjectManagement
			{
				get
				{
					return _testtestmale3projectmanagementInfo.CreateAdapter<Ranorex.ListItem>(true);
				}
			}

			/// <summary>
			/// The TestTestMale3ProjectManagement item info.
			/// </summary>
			[RepositoryItemInfo("a313a6f6-880b-4f31-b723-8e5920dd25bb")]
			public virtual RepoItemInfo TestTestMale3ProjectManagementInfo
			{
				get
				{
					return _testtestmale3projectmanagementInfo;
				}
			}
		}

		/// <summary>
		/// The RxTabUIElementsFolder folder.
		/// </summary>
		[RepositoryFolder("f08654ce-2eec-4bfd-b90d-36e5d1965cc1")]
		public partial class RxTabUIElementsFolder : RepoGenBaseFolder
		{
			RepoItemInfo _treeviewInfo;
			RepoItemInfo _rdbredlightInfo;
			RepoItemInfo _firstname行2Info;
			RepoItemInfo _webtestingInfo;

			/// <summary>
			/// Creates a new RxTabUIElements  folder.
			/// </summary>
			public RxTabUIElementsFolder(RepoGenBaseFolder parentFolder) :
					base("RxTabUIElements", "?/?/tabpage[@controlname='RxTabUIElements']", parentFolder, 30000, null, false, "f08654ce-2eec-4bfd-b90d-36e5d1965cc1", "")
			{
				_treeviewInfo = new RepoItemInfo(this, "TreeView", "?/?/tree[@accessiblename='Tree view']", 30000, null, "ccdc176f-cc75-4a2c-a2f8-44da66f28611");
				_rdbredlightInfo = new RepoItemInfo(this, "RdbRedLight", "container[@controlname='grpBox']/?/?/radiobutton[@controlname='rdbRedLight']", 30000, null, "8f248aaa-807d-4cd7-9803-a6a464c92340");
				_firstname行2Info = new RepoItemInfo(this, "FirstName行2", "table[@controlname='dataGridView1']/?/?/cell[@accessiblename='FirstName 行 2']", 30000, null, "44372e95-10b0-4321-914d-06baeb2241ab");
				_webtestingInfo = new RepoItemInfo(this, "WebTesting", "tree[@controlname='treTestTreeView']//treeitem[@accessiblename='Web testing']", 30000, null, "14b919d4-f305-4cd8-a58d-5150af660e0d");
			}

			/// <summary>
			/// The Self item.
			/// </summary>
			[RepositoryItem("f08654ce-2eec-4bfd-b90d-36e5d1965cc1")]
			public virtual Ranorex.TabPage Self
			{
				get
				{
					return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
				}
			}

			/// <summary>
			/// The Self item info.
			/// </summary>
			[RepositoryItemInfo("f08654ce-2eec-4bfd-b90d-36e5d1965cc1")]
			public virtual RepoItemInfo SelfInfo
			{
				get
				{
					return _selfInfo;
				}
			}

			/// <summary>
			/// The TreeView item.
			/// </summary>
			[RepositoryItem("ccdc176f-cc75-4a2c-a2f8-44da66f28611")]
			public virtual Ranorex.Tree TreeView
			{
				get
				{
					return _treeviewInfo.CreateAdapter<Ranorex.Tree>(true);
				}
			}

			/// <summary>
			/// The TreeView item info.
			/// </summary>
			[RepositoryItemInfo("ccdc176f-cc75-4a2c-a2f8-44da66f28611")]
			public virtual RepoItemInfo TreeViewInfo
			{
				get
				{
					return _treeviewInfo;
				}
			}

			/// <summary>
			/// The RdbRedLight item.
			/// </summary>
			[RepositoryItem("8f248aaa-807d-4cd7-9803-a6a464c92340")]
			public virtual Ranorex.RadioButton RdbRedLight
			{
				get
				{
					return _rdbredlightInfo.CreateAdapter<Ranorex.RadioButton>(true);
				}
			}

			/// <summary>
			/// The RdbRedLight item info.
			/// </summary>
			[RepositoryItemInfo("8f248aaa-807d-4cd7-9803-a6a464c92340")]
			public virtual RepoItemInfo RdbRedLightInfo
			{
				get
				{
					return _rdbredlightInfo;
				}
			}

			/// <summary>
			/// The FirstName行2 item.
			/// </summary>
			[RepositoryItem("44372e95-10b0-4321-914d-06baeb2241ab")]
			public virtual Ranorex.Cell FirstName行2
			{
				get
				{
					return _firstname行2Info.CreateAdapter<Ranorex.Cell>(true);
				}
			}

			/// <summary>
			/// The FirstName行2 item info.
			/// </summary>
			[RepositoryItemInfo("44372e95-10b0-4321-914d-06baeb2241ab")]
			public virtual RepoItemInfo FirstName行2Info
			{
				get
				{
					return _firstname行2Info;
				}
			}

			/// <summary>
			/// The WebTesting item.
			/// </summary>
			[RepositoryItem("14b919d4-f305-4cd8-a58d-5150af660e0d")]
			public virtual Ranorex.TreeItem WebTesting
			{
				get
				{
					return _webtestingInfo.CreateAdapter<Ranorex.TreeItem>(true);
				}
			}

			/// <summary>
			/// The WebTesting item info.
			/// </summary>
			[RepositoryItemInfo("14b919d4-f305-4cd8-a58d-5150af660e0d")]
			public virtual RepoItemInfo WebTestingInfo
			{
				get
				{
					return _webtestingInfo;
				}
			}
		}

		/// <summary>
		/// The List1000AppFolder folder.
		/// </summary>
		[RepositoryFolder("b3e9e1db-2ce3-4c39-9f2c-d1754c088064")]
		public partial class List1000AppFolder : RepoGenBaseFolder
		{
			RepoItemInfo _projectmanagementInfo;

			/// <summary>
			/// Creates a new List1000  folder.
			/// </summary>
			public List1000AppFolder(RepoGenBaseFolder parentFolder) :
					base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "b3e9e1db-2ce3-4c39-9f2c-d1754c088064", "")
			{
				_projectmanagementInfo = new RepoItemInfo(this, "ProjectManagement", "listitem[@text='Project Management']", 30000, null, "9672f707-03f0-425f-abaf-a77f4823b59f");
			}

			/// <summary>
			/// The Self item.
			/// </summary>
			[RepositoryItem("b3e9e1db-2ce3-4c39-9f2c-d1754c088064")]
			public virtual Ranorex.List Self
			{
				get
				{
					return _selfInfo.CreateAdapter<Ranorex.List>(true);
				}
			}

			/// <summary>
			/// The Self item info.
			/// </summary>
			[RepositoryItemInfo("b3e9e1db-2ce3-4c39-9f2c-d1754c088064")]
			public virtual RepoItemInfo SelfInfo
			{
				get
				{
					return _selfInfo;
				}
			}

			/// <summary>
			/// The ProjectManagement item.
			/// </summary>
			[RepositoryItem("9672f707-03f0-425f-abaf-a77f4823b59f")]
			public virtual Ranorex.ListItem ProjectManagement
			{
				get
				{
					return _projectmanagementInfo.CreateAdapter<Ranorex.ListItem>(true);
				}
			}

			/// <summary>
			/// The ProjectManagement item info.
			/// </summary>
			[RepositoryItemInfo("9672f707-03f0-425f-abaf-a77f4823b59f")]
			public virtual RepoItemInfo ProjectManagementInfo
			{
				get
				{
					return _projectmanagementInfo;
				}
			}
		}

		/// <summary>
		/// The WindowsApp電卓AppFolder folder.
		/// </summary>
		[RepositoryFolder("0da3aa8b-f7df-4a72-b48c-006148b8f305")]
		public partial class WindowsApp電卓AppFolder : RepoGenBaseFolder
		{
			sample_1RepositoryFolders.FlyoutNavFolder _flyoutnav;
			RepoItemInfo _sometextInfo;
			RepoItemInfo _text1Info;
			RepoItemInfo _navbuttonInfo;
			RepoItemInfo _listviewheaderitemInfo;
			RepoItemInfo _closeInfo;
			RepoItemInfo _num1buttonInfo;
			RepoItemInfo _negatebuttonInfo;
			RepoItemInfo _text2Info;
			RepoItemInfo _sometext1Info;
			RepoItemInfo _num6buttonInfo;
			RepoItemInfo _plusbuttonInfo;
			RepoItemInfo _sometext2Info;
			RepoItemInfo _num5buttonInfo;
			RepoItemInfo _multiplybuttonInfo;
			RepoItemInfo _num9buttonInfo;
			RepoItemInfo _clearbuttonInfo;
			RepoItemInfo _num7buttonInfo;
			RepoItemInfo _sometext3Info;
			RepoItemInfo _sometext4Info;
			RepoItemInfo _text5Info;
			RepoItemInfo _text6Info;
			RepoItemInfo _equalbuttonInfo;

			/// <summary>
			/// Creates a new WindowsApp電卓  folder.
			/// </summary>
			public WindowsApp電卓AppFolder(RepoGenBaseFolder parentFolder) :
					base("WindowsApp電卓", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "0da3aa8b-f7df-4a72-b48c-006148b8f305", "")
			{
				_flyoutnav = new sample_1RepositoryFolders.FlyoutNavFolder(this);
				_sometextInfo = new RepoItemInfo(this, "SomeText", "?/?/text[@name='']", 30000, null, "fa4f37ba-8dc4-4376-ac54-2c74b88bd7ee");
				_text1Info = new RepoItemInfo(this, "Text1", "?/?/button[@automationid='num1Button']/text[@name='1']", 30000, null, "53e0dc9c-765e-4367-98b1-ddc2d7120f1e");
				_navbuttonInfo = new RepoItemInfo(this, "NavButton", "button[@automationid='NavButton']", 30000, null, "4a6f2ab5-a4fb-43c2-9fdc-c35d8b7ce6d4");
				_listviewheaderitemInfo = new RepoItemInfo(this, "ListViewHeaderItem", "?/?/list[@automationid='FlyoutNav']/container[1]", 30000, null, "079ee58d-4263-428c-b884-7ad7ede8a9fa");
				_closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@automationid='Close']", 30000, null, "4b8fd04d-0b18-46ea-adec-111f51e31cc9");
				_num1buttonInfo = new RepoItemInfo(this, "Num1Button", "?/?/button[@automationid='num1Button']", 30000, null, "074db99a-0469-4da7-9c0b-ec317c3c90c3");
				_negatebuttonInfo = new RepoItemInfo(this, "NegateButton", "button[@automationid='negateButton']", 30000, null, "c9576e64-e112-4ac1-8ce8-92c6e2521617");
				_text2Info = new RepoItemInfo(this, "Text2", "?/?/button[@automationid='num2Button']/text[@name='2']", 30000, null, "ba3c2c1a-4c1c-4f67-b203-6a4370ba33e4");
				_sometext1Info = new RepoItemInfo(this, "SomeText1", "?/?/text[@name='']", 30000, null, "e68aa60c-1176-471d-af1a-e084ebd51262");
				_num6buttonInfo = new RepoItemInfo(this, "Num6Button", "?/?/button[@automationid='num6Button']", 30000, null, "85eb3b13-b32d-4c4b-837c-df65c2e522d8");
				_plusbuttonInfo = new RepoItemInfo(this, "PlusButton", "?/?/button[@automationid='plusButton']", 30000, null, "a29ebb3c-6529-43af-8247-f2ebd3dd2aad");
				_sometext2Info = new RepoItemInfo(this, "SomeText2", "?/?/button[@automationid='equalButton']/text[@name='']", 30000, null, "b753e6e5-02c8-48cd-911e-04ff0925d289");
				_num5buttonInfo = new RepoItemInfo(this, "Num5Button", "?/?/button[@automationid='num5Button']", 30000, null, "77a19e41-1aa2-4890-bdc6-7d2bc5e91e69");
				_multiplybuttonInfo = new RepoItemInfo(this, "MultiplyButton", "?/?/button[@automationid='multiplyButton']", 30000, null, "ef5f93b6-5508-4736-8ac2-1fcd1ff21270");
				_num9buttonInfo = new RepoItemInfo(this, "Num9Button", "?/?/button[@automationid='num9Button']", 30000, null, "be635bb4-7ea2-47a0-b51a-7353bda1c8a6");
				_clearbuttonInfo = new RepoItemInfo(this, "ClearButton", "?/?/button[@automationid='clearButton']", 30000, null, "0b153c89-1251-4033-8f9f-76bb023e48d3");
				_num7buttonInfo = new RepoItemInfo(this, "Num7Button", "?/?/button[@automationid='num7Button']", 30000, null, "c21272ca-64d7-4b0a-8efe-8ffc4c441525");
				_sometext3Info = new RepoItemInfo(this, "SomeText3", "?/?/button[@automationid='multiplyButton']/text[@name='']", 30000, null, "d401e8f0-7e11-45c4-8865-725fd1f5f206");
				_sometext4Info = new RepoItemInfo(this, "SomeText4", "?/?/button[@automationid='minusButton']/text[@name='']", 30000, null, "4c86e66d-cb3d-4bd9-b53a-b55e45b2a79f");
				_text5Info = new RepoItemInfo(this, "Text5", "?/?/button[@automationid='num5Button']/text[@name='5']", 30000, null, "05f13fb9-3cfb-4d92-a916-dd8cb6172472");
				_text6Info = new RepoItemInfo(this, "Text6", "?/?/button[@automationid='num6Button']/text[@name='6']", 30000, null, "3884d96a-633b-45f9-ba09-ce8b07d0d4a9");
				_equalbuttonInfo = new RepoItemInfo(this, "EqualButton", "?/?/button[@automationid='equalButton']", 30000, null, "3519ac26-2c0c-4a04-bea5-2443c7cf499e");
			}

			/// <summary>
			/// The Self item.
			/// </summary>
			[RepositoryItem("0da3aa8b-f7df-4a72-b48c-006148b8f305")]
			public virtual Ranorex.WindowsApp Self
			{
				get
				{
					return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
				}
			}

			/// <summary>
			/// The Self item info.
			/// </summary>
			[RepositoryItemInfo("0da3aa8b-f7df-4a72-b48c-006148b8f305")]
			public virtual RepoItemInfo SelfInfo
			{
				get
				{
					return _selfInfo;
				}
			}

			/// <summary>
			/// The SomeText item.
			/// </summary>
			[RepositoryItem("fa4f37ba-8dc4-4376-ac54-2c74b88bd7ee")]
			public virtual Ranorex.Text SomeText
			{
				get
				{
					return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
				}
			}

			/// <summary>
			/// The SomeText item info.
			/// </summary>
			[RepositoryItemInfo("fa4f37ba-8dc4-4376-ac54-2c74b88bd7ee")]
			public virtual RepoItemInfo SomeTextInfo
			{
				get
				{
					return _sometextInfo;
				}
			}

			/// <summary>
			/// The Text1 item.
			/// </summary>
			[RepositoryItem("53e0dc9c-765e-4367-98b1-ddc2d7120f1e")]
			public virtual Ranorex.Text Text1
			{
				get
				{
					return _text1Info.CreateAdapter<Ranorex.Text>(true);
				}
			}

			/// <summary>
			/// The Text1 item info.
			/// </summary>
			[RepositoryItemInfo("53e0dc9c-765e-4367-98b1-ddc2d7120f1e")]
			public virtual RepoItemInfo Text1Info
			{
				get
				{
					return _text1Info;
				}
			}

			/// <summary>
			/// The NavButton item.
			/// </summary>
			[RepositoryItem("4a6f2ab5-a4fb-43c2-9fdc-c35d8b7ce6d4")]
			public virtual Ranorex.Button NavButton
			{
				get
				{
					return _navbuttonInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The NavButton item info.
			/// </summary>
			[RepositoryItemInfo("4a6f2ab5-a4fb-43c2-9fdc-c35d8b7ce6d4")]
			public virtual RepoItemInfo NavButtonInfo
			{
				get
				{
					return _navbuttonInfo;
				}
			}

			/// <summary>
			/// The ListViewHeaderItem item.
			/// </summary>
			[RepositoryItem("079ee58d-4263-428c-b884-7ad7ede8a9fa")]
			public virtual Ranorex.Container ListViewHeaderItem
			{
				get
				{
					return _listviewheaderitemInfo.CreateAdapter<Ranorex.Container>(true);
				}
			}

			/// <summary>
			/// The ListViewHeaderItem item info.
			/// </summary>
			[RepositoryItemInfo("079ee58d-4263-428c-b884-7ad7ede8a9fa")]
			public virtual RepoItemInfo ListViewHeaderItemInfo
			{
				get
				{
					return _listviewheaderitemInfo;
				}
			}

			/// <summary>
			/// The Close item.
			/// </summary>
			[RepositoryItem("4b8fd04d-0b18-46ea-adec-111f51e31cc9")]
			public virtual Ranorex.Button Close
			{
				get
				{
					return _closeInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The Close item info.
			/// </summary>
			[RepositoryItemInfo("4b8fd04d-0b18-46ea-adec-111f51e31cc9")]
			public virtual RepoItemInfo CloseInfo
			{
				get
				{
					return _closeInfo;
				}
			}

			/// <summary>
			/// The Num1Button item.
			/// </summary>
			[RepositoryItem("074db99a-0469-4da7-9c0b-ec317c3c90c3")]
			public virtual Ranorex.Button Num1Button
			{
				get
				{
					return _num1buttonInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The Num1Button item info.
			/// </summary>
			[RepositoryItemInfo("074db99a-0469-4da7-9c0b-ec317c3c90c3")]
			public virtual RepoItemInfo Num1ButtonInfo
			{
				get
				{
					return _num1buttonInfo;
				}
			}

			/// <summary>
			/// The NegateButton item.
			/// </summary>
			[RepositoryItem("c9576e64-e112-4ac1-8ce8-92c6e2521617")]
			public virtual Ranorex.Button NegateButton
			{
				get
				{
					return _negatebuttonInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The NegateButton item info.
			/// </summary>
			[RepositoryItemInfo("c9576e64-e112-4ac1-8ce8-92c6e2521617")]
			public virtual RepoItemInfo NegateButtonInfo
			{
				get
				{
					return _negatebuttonInfo;
				}
			}

			/// <summary>
			/// The Text2 item.
			/// </summary>
			[RepositoryItem("ba3c2c1a-4c1c-4f67-b203-6a4370ba33e4")]
			public virtual Ranorex.Text Text2
			{
				get
				{
					return _text2Info.CreateAdapter<Ranorex.Text>(true);
				}
			}

			/// <summary>
			/// The Text2 item info.
			/// </summary>
			[RepositoryItemInfo("ba3c2c1a-4c1c-4f67-b203-6a4370ba33e4")]
			public virtual RepoItemInfo Text2Info
			{
				get
				{
					return _text2Info;
				}
			}

			/// <summary>
			/// The SomeText1 item.
			/// </summary>
			[RepositoryItem("e68aa60c-1176-471d-af1a-e084ebd51262")]
			public virtual Ranorex.Text SomeText1
			{
				get
				{
					return _sometext1Info.CreateAdapter<Ranorex.Text>(true);
				}
			}

			/// <summary>
			/// The SomeText1 item info.
			/// </summary>
			[RepositoryItemInfo("e68aa60c-1176-471d-af1a-e084ebd51262")]
			public virtual RepoItemInfo SomeText1Info
			{
				get
				{
					return _sometext1Info;
				}
			}

			/// <summary>
			/// The Num6Button item.
			/// </summary>
			[RepositoryItem("85eb3b13-b32d-4c4b-837c-df65c2e522d8")]
			public virtual Ranorex.Button Num6Button
			{
				get
				{
					return _num6buttonInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The Num6Button item info.
			/// </summary>
			[RepositoryItemInfo("85eb3b13-b32d-4c4b-837c-df65c2e522d8")]
			public virtual RepoItemInfo Num6ButtonInfo
			{
				get
				{
					return _num6buttonInfo;
				}
			}

			/// <summary>
			/// The PlusButton item.
			/// </summary>
			[RepositoryItem("a29ebb3c-6529-43af-8247-f2ebd3dd2aad")]
			public virtual Ranorex.Button PlusButton
			{
				get
				{
					return _plusbuttonInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The PlusButton item info.
			/// </summary>
			[RepositoryItemInfo("a29ebb3c-6529-43af-8247-f2ebd3dd2aad")]
			public virtual RepoItemInfo PlusButtonInfo
			{
				get
				{
					return _plusbuttonInfo;
				}
			}

			/// <summary>
			/// The SomeText2 item.
			/// </summary>
			[RepositoryItem("b753e6e5-02c8-48cd-911e-04ff0925d289")]
			public virtual Ranorex.Text SomeText2
			{
				get
				{
					return _sometext2Info.CreateAdapter<Ranorex.Text>(true);
				}
			}

			/// <summary>
			/// The SomeText2 item info.
			/// </summary>
			[RepositoryItemInfo("b753e6e5-02c8-48cd-911e-04ff0925d289")]
			public virtual RepoItemInfo SomeText2Info
			{
				get
				{
					return _sometext2Info;
				}
			}

			/// <summary>
			/// The Num5Button item.
			/// </summary>
			[RepositoryItem("77a19e41-1aa2-4890-bdc6-7d2bc5e91e69")]
			public virtual Ranorex.Button Num5Button
			{
				get
				{
					return _num5buttonInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The Num5Button item info.
			/// </summary>
			[RepositoryItemInfo("77a19e41-1aa2-4890-bdc6-7d2bc5e91e69")]
			public virtual RepoItemInfo Num5ButtonInfo
			{
				get
				{
					return _num5buttonInfo;
				}
			}

			/// <summary>
			/// The MultiplyButton item.
			/// </summary>
			[RepositoryItem("ef5f93b6-5508-4736-8ac2-1fcd1ff21270")]
			public virtual Ranorex.Button MultiplyButton
			{
				get
				{
					return _multiplybuttonInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The MultiplyButton item info.
			/// </summary>
			[RepositoryItemInfo("ef5f93b6-5508-4736-8ac2-1fcd1ff21270")]
			public virtual RepoItemInfo MultiplyButtonInfo
			{
				get
				{
					return _multiplybuttonInfo;
				}
			}

			/// <summary>
			/// The Num9Button item.
			/// </summary>
			[RepositoryItem("be635bb4-7ea2-47a0-b51a-7353bda1c8a6")]
			public virtual Ranorex.Button Num9Button
			{
				get
				{
					return _num9buttonInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The Num9Button item info.
			/// </summary>
			[RepositoryItemInfo("be635bb4-7ea2-47a0-b51a-7353bda1c8a6")]
			public virtual RepoItemInfo Num9ButtonInfo
			{
				get
				{
					return _num9buttonInfo;
				}
			}

			/// <summary>
			/// The ClearButton item.
			/// </summary>
			[RepositoryItem("0b153c89-1251-4033-8f9f-76bb023e48d3")]
			public virtual Ranorex.Button ClearButton
			{
				get
				{
					return _clearbuttonInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The ClearButton item info.
			/// </summary>
			[RepositoryItemInfo("0b153c89-1251-4033-8f9f-76bb023e48d3")]
			public virtual RepoItemInfo ClearButtonInfo
			{
				get
				{
					return _clearbuttonInfo;
				}
			}

			/// <summary>
			/// The Num7Button item.
			/// </summary>
			[RepositoryItem("c21272ca-64d7-4b0a-8efe-8ffc4c441525")]
			public virtual Ranorex.Button Num7Button
			{
				get
				{
					return _num7buttonInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The Num7Button item info.
			/// </summary>
			[RepositoryItemInfo("c21272ca-64d7-4b0a-8efe-8ffc4c441525")]
			public virtual RepoItemInfo Num7ButtonInfo
			{
				get
				{
					return _num7buttonInfo;
				}
			}

			/// <summary>
			/// The SomeText3 item.
			/// </summary>
			[RepositoryItem("d401e8f0-7e11-45c4-8865-725fd1f5f206")]
			public virtual Ranorex.Text SomeText3
			{
				get
				{
					return _sometext3Info.CreateAdapter<Ranorex.Text>(true);
				}
			}

			/// <summary>
			/// The SomeText3 item info.
			/// </summary>
			[RepositoryItemInfo("d401e8f0-7e11-45c4-8865-725fd1f5f206")]
			public virtual RepoItemInfo SomeText3Info
			{
				get
				{
					return _sometext3Info;
				}
			}

			/// <summary>
			/// The SomeText4 item.
			/// </summary>
			[RepositoryItem("4c86e66d-cb3d-4bd9-b53a-b55e45b2a79f")]
			public virtual Ranorex.Text SomeText4
			{
				get
				{
					return _sometext4Info.CreateAdapter<Ranorex.Text>(true);
				}
			}

			/// <summary>
			/// The SomeText4 item info.
			/// </summary>
			[RepositoryItemInfo("4c86e66d-cb3d-4bd9-b53a-b55e45b2a79f")]
			public virtual RepoItemInfo SomeText4Info
			{
				get
				{
					return _sometext4Info;
				}
			}

			/// <summary>
			/// The Text5 item.
			/// </summary>
			[RepositoryItem("05f13fb9-3cfb-4d92-a916-dd8cb6172472")]
			public virtual Ranorex.Text Text5
			{
				get
				{
					return _text5Info.CreateAdapter<Ranorex.Text>(true);
				}
			}

			/// <summary>
			/// The Text5 item info.
			/// </summary>
			[RepositoryItemInfo("05f13fb9-3cfb-4d92-a916-dd8cb6172472")]
			public virtual RepoItemInfo Text5Info
			{
				get
				{
					return _text5Info;
				}
			}

			/// <summary>
			/// The Text6 item.
			/// </summary>
			[RepositoryItem("3884d96a-633b-45f9-ba09-ce8b07d0d4a9")]
			public virtual Ranorex.Text Text6
			{
				get
				{
					return _text6Info.CreateAdapter<Ranorex.Text>(true);
				}
			}

			/// <summary>
			/// The Text6 item info.
			/// </summary>
			[RepositoryItemInfo("3884d96a-633b-45f9-ba09-ce8b07d0d4a9")]
			public virtual RepoItemInfo Text6Info
			{
				get
				{
					return _text6Info;
				}
			}

			/// <summary>
			/// The EqualButton item.
			/// </summary>
			[RepositoryItem("3519ac26-2c0c-4a04-bea5-2443c7cf499e")]
			public virtual Ranorex.Button EqualButton
			{
				get
				{
					return _equalbuttonInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The EqualButton item info.
			/// </summary>
			[RepositoryItemInfo("3519ac26-2c0c-4a04-bea5-2443c7cf499e")]
			public virtual RepoItemInfo EqualButtonInfo
			{
				get
				{
					return _equalbuttonInfo;
				}
			}

			/// <summary>
			/// The FlyoutNav folder.
			/// </summary>
			[RepositoryFolder("a47203dc-e199-46e1-99a5-95a3f8444d4d")]
			public virtual sample_1RepositoryFolders.FlyoutNavFolder FlyoutNav
			{
				get { return _flyoutnav; }
			}
		}

		/// <summary>
		/// The FlyoutNavFolder folder.
		/// </summary>
		[RepositoryFolder("a47203dc-e199-46e1-99a5-95a3f8444d4d")]
		public partial class FlyoutNavFolder : RepoGenBaseFolder
		{
			RepoItemInfo _標準電卓Info;
			RepoItemInfo _standardInfo;
			RepoItemInfo _電力動力コンバーターInfo;

			/// <summary>
			/// Creates a new FlyoutNav  folder.
			/// </summary>
			public FlyoutNavFolder(RepoGenBaseFolder parentFolder) :
					base("FlyoutNav", "?/?/list[@automationid='FlyoutNav']", parentFolder, 30000, null, false, "a47203dc-e199-46e1-99a5-95a3f8444d4d", "")
			{
				_標準電卓Info = new RepoItemInfo(this, "標準電卓", "?/?/listitem[@name='標準 電卓']", 30000, null, "354b641e-63af-459a-84c4-b09633e2de89");
				_standardInfo = new RepoItemInfo(this, "Standard", "?/?/listitem[@name='標準 電卓']/text[@automationid='Standard']", 30000, null, "3e5eb8f7-3be8-4598-804b-557ef6c06198");
				_電力動力コンバーターInfo = new RepoItemInfo(this, "電力動力コンバーター", "?/?/listitem[@name='電力/動力 コンバーター']", 30000, null, "1c9ef9c0-9e5d-4825-9b69-84c8841e6913");
			}

			/// <summary>
			/// The Self item.
			/// </summary>
			[RepositoryItem("a47203dc-e199-46e1-99a5-95a3f8444d4d")]
			public virtual Ranorex.List Self
			{
				get
				{
					return _selfInfo.CreateAdapter<Ranorex.List>(true);
				}
			}

			/// <summary>
			/// The Self item info.
			/// </summary>
			[RepositoryItemInfo("a47203dc-e199-46e1-99a5-95a3f8444d4d")]
			public virtual RepoItemInfo SelfInfo
			{
				get
				{
					return _selfInfo;
				}
			}

			/// <summary>
			/// The 標準電卓 item.
			/// </summary>
			[RepositoryItem("354b641e-63af-459a-84c4-b09633e2de89")]
			public virtual Ranorex.ListItem 標準電卓
			{
				get
				{
					return _標準電卓Info.CreateAdapter<Ranorex.ListItem>(true);
				}
			}

			/// <summary>
			/// The 標準電卓 item info.
			/// </summary>
			[RepositoryItemInfo("354b641e-63af-459a-84c4-b09633e2de89")]
			public virtual RepoItemInfo 標準電卓Info
			{
				get
				{
					return _標準電卓Info;
				}
			}

			/// <summary>
			/// The Standard item.
			/// </summary>
			[RepositoryItem("3e5eb8f7-3be8-4598-804b-557ef6c06198")]
			public virtual Ranorex.Text Standard
			{
				get
				{
					return _standardInfo.CreateAdapter<Ranorex.Text>(true);
				}
			}

			/// <summary>
			/// The Standard item info.
			/// </summary>
			[RepositoryItemInfo("3e5eb8f7-3be8-4598-804b-557ef6c06198")]
			public virtual RepoItemInfo StandardInfo
			{
				get
				{
					return _standardInfo;
				}
			}

			/// <summary>
			/// The 電力動力コンバーター item.
			/// </summary>
			[RepositoryItem("1c9ef9c0-9e5d-4825-9b69-84c8841e6913")]
			public virtual Ranorex.ListItem 電力動力コンバーター
			{
				get
				{
					return _電力動力コンバーターInfo.CreateAdapter<Ranorex.ListItem>(true);
				}
			}

			/// <summary>
			/// The 電力動力コンバーター item info.
			/// </summary>
			[RepositoryItemInfo("1c9ef9c0-9e5d-4825-9b69-84c8841e6913")]
			public virtual RepoItemInfo 電力動力コンバーターInfo
			{
				get
				{
					return _電力動力コンバーターInfo;
				}
			}
		}

	}
#pragma warning restore 0436
}
